# Generated by Django 2.2 on 2019-04-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatarcode',
            field=models.CharField(default='&#64;', max_length=8, verbose_name='Avatar Code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tosaccepted',
            field=models.BooleanField(default=False, verbose_name='TOS Accepted'),
        ),
    ]
